// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/filesystem-service/v1/resources/filesystem.common.resource.v1.proto

package filesystemv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	filesystemerrorv1 "gitlab.lainuoniao.cn/eden-quan/proto-service/api/filesystem-service/v1/errors"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = filesystemerrorv1.FILEIO_ERROR(0)
)

// Validate checks the field values on FSCommonRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *FSCommonRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FSCommonRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FSCommonRequestMultiError, or nil if none found.
func (m *FSCommonRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FSCommonRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Path

	if len(errors) > 0 {
		return FSCommonRequestMultiError(errors)
	}

	return nil
}

// FSCommonRequestMultiError is an error wrapping multiple validation errors
// returned by FSCommonRequest.ValidateAll() if the designated constraints
// aren't met.
type FSCommonRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FSCommonRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FSCommonRequestMultiError) AllErrors() []error { return m }

// FSCommonRequestValidationError is the validation error returned by
// FSCommonRequest.Validate if the designated constraints aren't met.
type FSCommonRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FSCommonRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FSCommonRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FSCommonRequestValidationError) Cause() error { return e.cause }

func (e FSCommonRequestValidationError) Code() int64 { return 10010001 }

func (e FSCommonRequestValidationError) HttpCode() int64 { return 400 }

// Key function returns key value.
func (e FSCommonRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FSCommonRequestValidationError) ErrorName() string { return "FSCommonRequestValidationError" }

// Error satisfies the builtin error interface
func (e FSCommonRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFSCommonRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FSCommonRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Code() int64
	HttpCode() int64
	Cause() error
	ErrorName() string
} = FSCommonRequestValidationError{}

// Validate checks the field values on FSCommonReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FSCommonReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FSCommonReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FSCommonReplyMultiError, or
// nil if none found.
func (m *FSCommonReply) ValidateAll() error {
	return m.validate(true)
}

func (m *FSCommonReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return FSCommonReplyMultiError(errors)
	}

	return nil
}

// FSCommonReplyMultiError is an error wrapping multiple validation errors
// returned by FSCommonReply.ValidateAll() if the designated constraints
// aren't met.
type FSCommonReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FSCommonReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FSCommonReplyMultiError) AllErrors() []error { return m }

// FSCommonReplyValidationError is the validation error returned by
// FSCommonReply.Validate if the designated constraints aren't met.
type FSCommonReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FSCommonReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FSCommonReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FSCommonReplyValidationError) Cause() error { return e.cause }

func (e FSCommonReplyValidationError) Code() int64 { return 10010001 }

func (e FSCommonReplyValidationError) HttpCode() int64 { return 400 }

// Key function returns key value.
func (e FSCommonReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FSCommonReplyValidationError) ErrorName() string { return "FSCommonReplyValidationError" }

// Error satisfies the builtin error interface
func (e FSCommonReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFSCommonReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FSCommonReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Code() int64
	HttpCode() int64
	Cause() error
	ErrorName() string
} = FSCommonReplyValidationError{}
