// Code generated by protoc-gen-go-fx. DO NOT EDIT.
// versions:
// 	protoc-gen-go-fx v1.32.0-devel
// 	protoc        v5.26.1
// source: api/iam-service/v1/errors/iam.iam.error.v1.proto

package iamerrorv1

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ERROR .
type IAM_ERROR int32

const (
	IAM_ERROR_IAM_UNKNOWN         IAM_ERROR = 0
	IAM_ERROR_IAM_CONTENT_MISSING IAM_ERROR = 100000001
	IAM_ERROR_IAM_CONTENT_ERROR   IAM_ERROR = 100000002
)

// Enum value maps for IAM_ERROR.
var (
	IAM_ERROR_name = map[int32]string{
		0:         "IAM_UNKNOWN",
		100000001: "IAM_CONTENT_MISSING",
		100000002: "IAM_CONTENT_ERROR",
	}
	IAM_ERROR_value = map[string]int32{
		"IAM_UNKNOWN":         0,
		"IAM_CONTENT_MISSING": 100000001,
		"IAM_CONTENT_ERROR":   100000002,
	}
)

func (x IAM_ERROR) Enum() *IAM_ERROR {
	p := new(IAM_ERROR)
	*p = x
	return p
}

func (x IAM_ERROR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IAM_ERROR) Descriptor() protoreflect.EnumDescriptor {
	return file_api_iam_service_v1_errors_iam_iam_error_v1_proto_enumTypes[0].Descriptor()
}

func (IAM_ERROR) Type() protoreflect.EnumType {
	return &file_api_iam_service_v1_errors_iam_iam_error_v1_proto_enumTypes[0]
}

func (x IAM_ERROR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IAM_ERROR.Descriptor instead.
func (IAM_ERROR) EnumDescriptor() ([]byte, []int) {
	return file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDescGZIP(), []int{0}
}

var File_api_iam_service_v1_errors_iam_iam_error_v1_proto protoreflect.FileDescriptor

var file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDesc = []byte{
	0x0a, 0x30, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x61, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x69, 0x61, 0x6d, 0x2e,
	0x69, 0x61, 0x6d, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1a, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x69, 0x61, 0x6d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x76, 0x31, 0x1a, 0x13,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2a, 0x6a, 0x0a, 0x09, 0x49, 0x41, 0x4d, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x12, 0x15, 0x0a, 0x0b, 0x49, 0x41, 0x4d, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x1a, 0x04, 0xa8, 0x45, 0x94, 0x03, 0x12, 0x20, 0x0a, 0x13, 0x49, 0x41, 0x4d, 0x5f, 0x43,
	0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x81,
	0xc2, 0xd7, 0x2f, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x12, 0x1e, 0x0a, 0x11, 0x49, 0x41, 0x4d,
	0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x82,
	0xc2, 0xd7, 0x2f, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42,
	0x53, 0x5a, 0x51, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6c, 0x61, 0x69, 0x6e, 0x75, 0x6f,
	0x6e, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6e, 0x2f, 0x65, 0x64, 0x65, 0x6e, 0x2d, 0x71, 0x75, 0x61,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x69, 0x61, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x3b, 0x69, 0x61, 0x6d, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDescOnce sync.Once
	file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDescData = file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDesc
)

func file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDescGZIP() []byte {
	file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDescOnce.Do(func() {
		file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDescData)
	})
	return file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDescData
}

var file_api_iam_service_v1_errors_iam_iam_error_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_iam_service_v1_errors_iam_iam_error_v1_proto_goTypes = []interface{}{
	(IAM_ERROR)(0), // 0: api.iam.service.iamerrorv1.IAM_ERROR
}
var file_api_iam_service_v1_errors_iam_iam_error_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_iam_service_v1_errors_iam_iam_error_v1_proto_init() }
func file_api_iam_service_v1_errors_iam_iam_error_v1_proto_init() {
	if File_api_iam_service_v1_errors_iam_iam_error_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_iam_service_v1_errors_iam_iam_error_v1_proto_goTypes,
		DependencyIndexes: file_api_iam_service_v1_errors_iam_iam_error_v1_proto_depIdxs,
		EnumInfos:         file_api_iam_service_v1_errors_iam_iam_error_v1_proto_enumTypes,
	}.Build()
	File_api_iam_service_v1_errors_iam_iam_error_v1_proto = out.File
	file_api_iam_service_v1_errors_iam_iam_error_v1_proto_rawDesc = nil
	file_api_iam_service_v1_errors_iam_iam_error_v1_proto_goTypes = nil
	file_api_iam_service_v1_errors_iam_iam_error_v1_proto_depIdxs = nil
}
