// Code generated by protoc-gen-go-fx. DO NOT EDIT.
// versions:
// 	protoc-gen-go-fx v1.32.0-devel
// 	protoc        v5.26.1
// source: api/iam-service/v1/enums/iam.iam.enum.v1.proto

package iamenumv1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingInit enum
type IamInitEnum_IamInit int32

const (
	// UNSPECIFIED 未指定
	IamInitEnum_UNSPECIFIED IamInitEnum_IamInit = 0
)

// Enum value maps for IamInitEnum_IamInit.
var (
	IamInitEnum_IamInit_name = map[int32]string{
		0: "UNSPECIFIED",
	}
	IamInitEnum_IamInit_value = map[string]int32{
		"UNSPECIFIED": 0,
	}
)

func (x IamInitEnum_IamInit) Enum() *IamInitEnum_IamInit {
	p := new(IamInitEnum_IamInit)
	*p = x
	return p
}

func (x IamInitEnum_IamInit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IamInitEnum_IamInit) Descriptor() protoreflect.EnumDescriptor {
	return file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_enumTypes[0].Descriptor()
}

func (IamInitEnum_IamInit) Type() protoreflect.EnumType {
	return &file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_enumTypes[0]
}

func (x IamInitEnum_IamInit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IamInitEnum_IamInit.Descriptor instead.
func (IamInitEnum_IamInit) EnumDescriptor() ([]byte, []int) {
	return file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDescGZIP(), []int{0, 0}
}

// IamServiceInitEnum enum
type IamInitEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IamInitEnum) Reset() {
	*x = IamInitEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IamInitEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IamInitEnum) ProtoMessage() {}

func (x *IamInitEnum) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IamInitEnum.ProtoReflect.Descriptor instead.
func (*IamInitEnum) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDescGZIP(), []int{0}
}

var File_api_iam_service_v1_enums_iam_iam_enum_v1_proto protoreflect.FileDescriptor

var file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x61, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x69, 0x61, 0x6d, 0x2e, 0x69,
	0x61, 0x6d, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x19, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x69, 0x61, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x76, 0x31, 0x22, 0x29, 0x0a, 0x0b, 0x49,
	0x61, 0x6d, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x1a, 0x0a, 0x07, 0x49, 0x61,
	0x6d, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x42, 0x51, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2e, 0x6c, 0x61, 0x69, 0x6e, 0x75, 0x6f, 0x6e, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6e, 0x2f, 0x65,
	0x64, 0x65, 0x6e, 0x2d, 0x71, 0x75, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x61, 0x6d, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x3b,
	0x69, 0x61, 0x6d, 0x65, 0x6e, 0x75, 0x6d, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDescOnce sync.Once
	file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDescData = file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDesc
)

func file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDescGZIP() []byte {
	file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDescOnce.Do(func() {
		file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDescData)
	})
	return file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDescData
}

var file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_goTypes = []interface{}{
	(IamInitEnum_IamInit)(0), // 0: api.iam.service.iamenumv1.IamInitEnum.IamInit
	(*IamInitEnum)(nil),      // 1: api.iam.service.iamenumv1.IamInitEnum
}
var file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_init() }
func file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_init() {
	if File_api_iam_service_v1_enums_iam_iam_enum_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IamInitEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_goTypes,
		DependencyIndexes: file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_depIdxs,
		EnumInfos:         file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_enumTypes,
		MessageInfos:      file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_msgTypes,
	}.Build()
	File_api_iam_service_v1_enums_iam_iam_enum_v1_proto = out.File
	file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_rawDesc = nil
	file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_goTypes = nil
	file_api_iam_service_v1_enums_iam_iam_enum_v1_proto_depIdxs = nil
}
