// Code generated by protoc-gen-go-fx. DO NOT EDIT.
// versions:
// 	protoc-gen-go-fx v1.32.0-devel
// 	protoc        v5.26.1
// source: api/iam-service/v1/resources/iam.user.resource.v1.proto

package iamv1

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid                    int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                       //////unique
	AccessToken            string `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`                        //////output only
	RefreshToken           string `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`                      //////output only
	RefreshTokenExpireTime int64  `protobuf:"varint,4,opt,name=refreshTokenExpireTime,proto3" json:"refreshTokenExpireTime,omitempty"` //////output only
	AccessTokenExpireTime  int64  `protobuf:"varint,5,opt,name=accessTokenExpireTime,proto3" json:"accessTokenExpireTime,omitempty"`   //////output only
	RegisterType           int32  `protobuf:"varint,6,opt,name=registerType,proto3" json:"registerType,omitempty"`                     //////output only
	CompanyId              int64  `protobuf:"varint,7,opt,name=companyId,proto3" json:"companyId,omitempty"`
	CompanyLabel           int32  `protobuf:"varint,8,opt,name=companyLabel,proto3" json:"companyLabel,omitempty"`
}

func (x *UserUser) Reset() {
	*x = UserUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUser) ProtoMessage() {}

func (x *UserUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUser.ProtoReflect.Descriptor instead.
func (*UserUser) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{0}
}

func (x *UserUser) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserUser) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserUser) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *UserUser) GetRefreshTokenExpireTime() int64 {
	if x != nil {
		return x.RefreshTokenExpireTime
	}
	return 0
}

func (x *UserUser) GetAccessTokenExpireTime() int64 {
	if x != nil {
		return x.AccessTokenExpireTime
	}
	return 0
}

func (x *UserUser) GetRegisterType() int32 {
	if x != nil {
		return x.RegisterType
	}
	return 0
}

func (x *UserUser) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *UserUser) GetCompanyLabel() int32 {
	if x != nil {
		return x.CompanyLabel
	}
	return 0
}

type UserCheckLastLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UserCheckLastLoginRequest) Reset() {
	*x = UserCheckLastLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCheckLastLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCheckLastLoginRequest) ProtoMessage() {}

func (x *UserCheckLastLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCheckLastLoginRequest.ProtoReflect.Descriptor instead.
func (*UserCheckLastLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{1}
}

func (x *UserCheckLastLoginRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserCheckLastLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Yes bool `protobuf:"varint,1,opt,name=yes,proto3" json:"yes,omitempty"`
}

func (x *UserCheckLastLoginResponse) Reset() {
	*x = UserCheckLastLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCheckLastLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCheckLastLoginResponse) ProtoMessage() {}

func (x *UserCheckLastLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCheckLastLoginResponse.ProtoReflect.Descriptor instead.
func (*UserCheckLastLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{2}
}

func (x *UserCheckLastLoginResponse) GetYes() bool {
	if x != nil {
		return x.Yes
	}
	return false
}

type UserUserLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid           int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KickLastLogin bool  `protobuf:"varint,2,opt,name=kickLastLogin,proto3" json:"kickLastLogin,omitempty"` // if kick last login user off
	CompanyId     int64 `protobuf:"varint,3,opt,name=companyId,proto3" json:"companyId,omitempty"`
	CompanyLabel  int32 `protobuf:"varint,4,opt,name=companyLabel,proto3" json:"companyLabel,omitempty"`
}

func (x *UserUserLoginRequest) Reset() {
	*x = UserUserLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUserLoginRequest) ProtoMessage() {}

func (x *UserUserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserUserLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{3}
}

func (x *UserUserLoginRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserUserLoginRequest) GetKickLastLogin() bool {
	if x != nil {
		return x.KickLastLogin
	}
	return false
}

func (x *UserUserLoginRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *UserUserLoginRequest) GetCompanyLabel() int32 {
	if x != nil {
		return x.CompanyLabel
	}
	return 0
}

type UserUserLogoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// uid
	IsLogoutByUid bool  `protobuf:"varint,2,opt,name=isLogoutByUid,proto3" json:"isLogoutByUid,omitempty"`
	Uid           int64 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UserUserLogoutRequest) Reset() {
	*x = UserUserLogoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUserLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUserLogoutRequest) ProtoMessage() {}

func (x *UserUserLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUserLogoutRequest.ProtoReflect.Descriptor instead.
func (*UserUserLogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{4}
}

func (x *UserUserLogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserUserLogoutRequest) GetIsLogoutByUid() bool {
	if x != nil {
		return x.IsLogoutByUid
	}
	return false
}

func (x *UserUserLogoutRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserUserLogoutReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken string `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
}

func (x *UserUserLogoutReply) Reset() {
	*x = UserUserLogoutReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUserLogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUserLogoutReply) ProtoMessage() {}

func (x *UserUserLogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUserLogoutReply.ProtoReflect.Descriptor instead.
func (*UserUserLogoutReply) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{5}
}

func (x *UserUserLogoutReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UserUserRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAutoLogin  bool  `protobuf:"varint,1,opt,name=isAutoLogin,proto3" json:"isAutoLogin,omitempty"`
	RegisterType int32 `protobuf:"varint,2,opt,name=registerType,proto3" json:"registerType,omitempty"` // 0 design company 1 supplierCompany 2 platform company
	CompanyId    int64 `protobuf:"varint,3,opt,name=companyId,proto3" json:"companyId,omitempty"`
	CompanyLabel int32 `protobuf:"varint,4,opt,name=companyLabel,proto3" json:"companyLabel,omitempty"`
}

func (x *UserUserRegisterRequest) Reset() {
	*x = UserUserRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUserRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUserRegisterRequest) ProtoMessage() {}

func (x *UserUserRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUserRegisterRequest.ProtoReflect.Descriptor instead.
func (*UserUserRegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{6}
}

func (x *UserUserRegisterRequest) GetIsAutoLogin() bool {
	if x != nil {
		return x.IsAutoLogin
	}
	return false
}

func (x *UserUserRegisterRequest) GetRegisterType() int32 {
	if x != nil {
		return x.RegisterType
	}
	return 0
}

func (x *UserUserRegisterRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *UserUserRegisterRequest) GetCompanyLabel() int32 {
	if x != nil {
		return x.CompanyLabel
	}
	return 0
}

type UserCheckTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *UserCheckTokenRequest) Reset() {
	*x = UserCheckTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCheckTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCheckTokenRequest) ProtoMessage() {}

func (x *UserCheckTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCheckTokenRequest.ProtoReflect.Descriptor instead.
func (*UserCheckTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{7}
}

func (x *UserCheckTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserCheckTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result                 int32  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Uid                    string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	RefreshToken           string `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	RefreshTokenExpireTime int64  `protobuf:"varint,4,opt,name=refreshTokenExpireTime,proto3" json:"refreshTokenExpireTime,omitempty"`
	RegisterType           int32  `protobuf:"varint,5,opt,name=registerType,proto3" json:"registerType,omitempty"`
	CompanyId              int64  `protobuf:"varint,6,opt,name=companyId,proto3" json:"companyId,omitempty"`
	CompanyLabel           int32  `protobuf:"varint,8,opt,name=companyLabel,proto3" json:"companyLabel,omitempty"`
}

func (x *UserCheckTokenResponse) Reset() {
	*x = UserCheckTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCheckTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCheckTokenResponse) ProtoMessage() {}

func (x *UserCheckTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCheckTokenResponse.ProtoReflect.Descriptor instead.
func (*UserCheckTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{8}
}

func (x *UserCheckTokenResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *UserCheckTokenResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserCheckTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *UserCheckTokenResponse) GetRefreshTokenExpireTime() int64 {
	if x != nil {
		return x.RefreshTokenExpireTime
	}
	return 0
}

func (x *UserCheckTokenResponse) GetRegisterType() int32 {
	if x != nil {
		return x.RegisterType
	}
	return 0
}

func (x *UserCheckTokenResponse) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *UserCheckTokenResponse) GetCompanyLabel() int32 {
	if x != nil {
		return x.CompanyLabel
	}
	return 0
}

type UserCheckUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UserCheckUserRequest) Reset() {
	*x = UserCheckUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCheckUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCheckUserRequest) ProtoMessage() {}

func (x *UserCheckUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCheckUserRequest.ProtoReflect.Descriptor instead.
func (*UserCheckUserRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{9}
}

func (x *UserCheckUserRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type UserCheckUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UserCheckUserResponse) Reset() {
	*x = UserCheckUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCheckUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCheckUserResponse) ProtoMessage() {}

func (x *UserCheckUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCheckUserResponse.ProtoReflect.Descriptor instead.
func (*UserCheckUserResponse) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{10}
}

func (x *UserCheckUserResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type UserRefreshTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken string `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
}

func (x *UserRefreshTokenRequest) Reset() {
	*x = UserRefreshTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRefreshTokenRequest) ProtoMessage() {}

func (x *UserRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*UserRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{11}
}

func (x *UserRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UserRefreshTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken            string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken           string `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	RefreshTokenExpireTime int64  `protobuf:"varint,3,opt,name=refreshTokenExpireTime,proto3" json:"refreshTokenExpireTime,omitempty"`
	AccessTokenExpireTime  int64  `protobuf:"varint,4,opt,name=accessTokenExpireTime,proto3" json:"accessTokenExpireTime,omitempty"`
	CompanyId              int64  `protobuf:"varint,7,opt,name=companyId,proto3" json:"companyId,omitempty"`
	CompanyLabel           int32  `protobuf:"varint,8,opt,name=companyLabel,proto3" json:"companyLabel,omitempty"`
}

func (x *UserRefreshTokenResponse) Reset() {
	*x = UserRefreshTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRefreshTokenResponse) ProtoMessage() {}

func (x *UserRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*UserRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{12}
}

func (x *UserRefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserRefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *UserRefreshTokenResponse) GetRefreshTokenExpireTime() int64 {
	if x != nil {
		return x.RefreshTokenExpireTime
	}
	return 0
}

func (x *UserRefreshTokenResponse) GetAccessTokenExpireTime() int64 {
	if x != nil {
		return x.AccessTokenExpireTime
	}
	return 0
}

func (x *UserRefreshTokenResponse) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *UserRefreshTokenResponse) GetCompanyLabel() int32 {
	if x != nil {
		return x.CompanyLabel
	}
	return 0
}

type UserDeleteUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UidList         []int64 `protobuf:"varint,1,rep,packed,name=uidList,proto3" json:"uidList,omitempty"`
	IsOnlyUserToken bool    `protobuf:"varint,2,opt,name=isOnlyUserToken,proto3" json:"isOnlyUserToken,omitempty"`
}

func (x *UserDeleteUserRequest) Reset() {
	*x = UserDeleteUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteUserRequest) ProtoMessage() {}

func (x *UserDeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteUserRequest.ProtoReflect.Descriptor instead.
func (*UserDeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{13}
}

func (x *UserDeleteUserRequest) GetUidList() []int64 {
	if x != nil {
		return x.UidList
	}
	return nil
}

func (x *UserDeleteUserRequest) GetIsOnlyUserToken() bool {
	if x != nil {
		return x.IsOnlyUserToken
	}
	return false
}

type UserDeleteUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserDeleteUserResponse) Reset() {
	*x = UserDeleteUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteUserResponse) ProtoMessage() {}

func (x *UserDeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteUserResponse.ProtoReflect.Descriptor instead.
func (*UserDeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{14}
}

type UserUpdateCompanyIdAndLabelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken string `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	CompanyId    int64  `protobuf:"varint,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	CompanyLabel int32  `protobuf:"varint,3,opt,name=companyLabel,proto3" json:"companyLabel,omitempty"`
	Uid          int64  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"` // if refresh token is empty,then update by uid
}

func (x *UserUpdateCompanyIdAndLabelRequest) Reset() {
	*x = UserUpdateCompanyIdAndLabelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdateCompanyIdAndLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateCompanyIdAndLabelRequest) ProtoMessage() {}

func (x *UserUpdateCompanyIdAndLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateCompanyIdAndLabelRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateCompanyIdAndLabelRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{15}
}

func (x *UserUpdateCompanyIdAndLabelRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *UserUpdateCompanyIdAndLabelRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *UserUpdateCompanyIdAndLabelRequest) GetCompanyLabel() int32 {
	if x != nil {
		return x.CompanyLabel
	}
	return 0
}

func (x *UserUpdateCompanyIdAndLabelRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserUpdateCompanyIdAndLabelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UserUpdateCompanyIdAndLabelResponse) Reset() {
	*x = UserUpdateCompanyIdAndLabelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdateCompanyIdAndLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateCompanyIdAndLabelResponse) ProtoMessage() {}

func (x *UserUpdateCompanyIdAndLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateCompanyIdAndLabelResponse.ProtoReflect.Descriptor instead.
func (*UserUpdateCompanyIdAndLabelResponse) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP(), []int{16}
}

func (x *UserUpdateCompanyIdAndLabelResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserUpdateCompanyIdAndLabelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_iam_service_v1_resources_iam_user_resource_v1_proto protoreflect.FileDescriptor

var file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDesc = []byte{
	0x0a, 0x37, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x61, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x69,
	0x61, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61, 0x70, 0x69, 0x2e, 0x69,
	0x61, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x61, 0x6d, 0x76, 0x31,
	0x1a, 0x23, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6, 0x02, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x36, 0x0a, 0x16, 0x72, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x16, 0x72, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x34, 0x0a, 0x15, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x15, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x2d,
	0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x61, 0x73, 0x74, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x2e, 0x0a,
	0x1a, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x79,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x79, 0x65, 0x73, 0x22, 0x90, 0x01,
	0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6b, 0x69, 0x63, 0x6b,
	0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0d, 0x6b, 0x69, 0x63, 0x6b, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x22, 0x65, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x24, 0x0a, 0x0d, 0x69, 0x73, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x55, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74,
	0x42, 0x79, 0x55, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22,
	0x0a, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0xa1, 0x01, 0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x69, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x2d, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x84, 0x02, 0x0a, 0x16, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x36,
	0x0a, 0x16, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x16,
	0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x28, 0x0a, 0x14,
	0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3d, 0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x90, 0x02, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x36, 0x0a, 0x16, 0x72, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x16, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x34, 0x0a, 0x15, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x15, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x5b, 0x0a, 0x15, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x07, 0x75, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f,
	0x69, 0x73, 0x4f, 0x6e, 0x6c, 0x79, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x4f, 0x6e, 0x6c, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x9c, 0x01, 0x0a, 0x22, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x41, 0x6e, 0x64, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22,
	0x53, 0x0a, 0x23, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x41, 0x6e, 0x64, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x5c, 0x8a, 0x43, 0x08, 0x08, 0x91, 0xfb, 0xe2, 0x04, 0x10, 0x90,
	0x03, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6c, 0x61, 0x69, 0x6e, 0x75, 0x6f,
	0x6e, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6e, 0x2f, 0x65, 0x64, 0x65, 0x6e, 0x2d, 0x71, 0x75, 0x61,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x69, 0x61, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x3b, 0x69, 0x61, 0x6d,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescOnce sync.Once
	file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescData = file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDesc
)

func file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescGZIP() []byte {
	file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescOnce.Do(func() {
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescData)
	})
	return file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDescData
}

var file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_iam_service_v1_resources_iam_user_resource_v1_proto_goTypes = []interface{}{
	(*UserUser)(nil),                            // 0: api.iam.service.iamv1.UserUser
	(*UserCheckLastLoginRequest)(nil),           // 1: api.iam.service.iamv1.UserCheckLastLoginRequest
	(*UserCheckLastLoginResponse)(nil),          // 2: api.iam.service.iamv1.UserCheckLastLoginResponse
	(*UserUserLoginRequest)(nil),                // 3: api.iam.service.iamv1.UserUserLoginRequest
	(*UserUserLogoutRequest)(nil),               // 4: api.iam.service.iamv1.UserUserLogoutRequest
	(*UserUserLogoutReply)(nil),                 // 5: api.iam.service.iamv1.UserUserLogoutReply
	(*UserUserRegisterRequest)(nil),             // 6: api.iam.service.iamv1.UserUserRegisterRequest
	(*UserCheckTokenRequest)(nil),               // 7: api.iam.service.iamv1.UserCheckTokenRequest
	(*UserCheckTokenResponse)(nil),              // 8: api.iam.service.iamv1.UserCheckTokenResponse
	(*UserCheckUserRequest)(nil),                // 9: api.iam.service.iamv1.UserCheckUserRequest
	(*UserCheckUserResponse)(nil),               // 10: api.iam.service.iamv1.UserCheckUserResponse
	(*UserRefreshTokenRequest)(nil),             // 11: api.iam.service.iamv1.UserRefreshTokenRequest
	(*UserRefreshTokenResponse)(nil),            // 12: api.iam.service.iamv1.UserRefreshTokenResponse
	(*UserDeleteUserRequest)(nil),               // 13: api.iam.service.iamv1.UserDeleteUserRequest
	(*UserDeleteUserResponse)(nil),              // 14: api.iam.service.iamv1.UserDeleteUserResponse
	(*UserUpdateCompanyIdAndLabelRequest)(nil),  // 15: api.iam.service.iamv1.UserUpdateCompanyIdAndLabelRequest
	(*UserUpdateCompanyIdAndLabelResponse)(nil), // 16: api.iam.service.iamv1.UserUpdateCompanyIdAndLabelResponse
}
var file_api_iam_service_v1_resources_iam_user_resource_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_iam_service_v1_resources_iam_user_resource_v1_proto_init() }
func file_api_iam_service_v1_resources_iam_user_resource_v1_proto_init() {
	if File_api_iam_service_v1_resources_iam_user_resource_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCheckLastLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCheckLastLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUserLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUserLogoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUserLogoutReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUserRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCheckTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCheckTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCheckUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCheckUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRefreshTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRefreshTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDeleteUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDeleteUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdateCompanyIdAndLabelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdateCompanyIdAndLabelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_iam_service_v1_resources_iam_user_resource_v1_proto_goTypes,
		DependencyIndexes: file_api_iam_service_v1_resources_iam_user_resource_v1_proto_depIdxs,
		MessageInfos:      file_api_iam_service_v1_resources_iam_user_resource_v1_proto_msgTypes,
	}.Build()
	File_api_iam_service_v1_resources_iam_user_resource_v1_proto = out.File
	file_api_iam_service_v1_resources_iam_user_resource_v1_proto_rawDesc = nil
	file_api_iam_service_v1_resources_iam_user_resource_v1_proto_goTypes = nil
	file_api_iam_service_v1_resources_iam_user_resource_v1_proto_depIdxs = nil
}
