// Code generated by protoc-gen-go-fx. DO NOT EDIT.
// versions:
// 	protoc-gen-go-fx v1.32.0-devel
// 	protoc        v5.26.1
// source: api/iam-service/v1/resources/iam.api.resource.v1.proto

package iamv1

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APICreateGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Uid         int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *APICreateGroupRequest) Reset() {
	*x = APICreateGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APICreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICreateGroupRequest) ProtoMessage() {}

func (x *APICreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICreateGroupRequest.ProtoReflect.Descriptor instead.
func (*APICreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{0}
}

func (x *APICreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APICreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *APICreateGroupRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type APICreateGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GourpId string `protobuf:"bytes,1,opt,name=gourpId,proto3" json:"gourpId,omitempty"`
}

func (x *APICreateGroupReply) Reset() {
	*x = APICreateGroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APICreateGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICreateGroupReply) ProtoMessage() {}

func (x *APICreateGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICreateGroupReply.ProtoReflect.Descriptor instead.
func (*APICreateGroupReply) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{1}
}

func (x *APICreateGroupReply) GetGourpId() string {
	if x != nil {
		return x.GourpId
	}
	return ""
}

type APIGetGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *APIGetGroupRequest) Reset() {
	*x = APIGetGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIGetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetGroupRequest) ProtoMessage() {}

func (x *APIGetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetGroupRequest.ProtoReflect.Descriptor instead.
func (*APIGetGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{2}
}

func (x *APIGetGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type APIDeleteGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *APIDeleteGroupRequest) Reset() {
	*x = APIDeleteGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIDeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDeleteGroupRequest) ProtoMessage() {}

func (x *APIDeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*APIDeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{3}
}

func (x *APIDeleteGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type APIDeleteGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIDeleteGroupReply) Reset() {
	*x = APIDeleteGroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIDeleteGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDeleteGroupReply) ProtoMessage() {}

func (x *APIDeleteGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDeleteGroupReply.ProtoReflect.Descriptor instead.
func (*APIDeleteGroupReply) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{4}
}

type APIGroupMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId string `protobuf:"bytes,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	// 0 user 1 serviceaccount 2 group
	MemberType int32 `protobuf:"varint,2,opt,name=memberType,proto3" json:"memberType,omitempty"`
}

func (x *APIGroupMember) Reset() {
	*x = APIGroupMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIGroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGroupMember) ProtoMessage() {}

func (x *APIGroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGroupMember.ProtoReflect.Descriptor instead.
func (*APIGroupMember) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{5}
}

func (x *APIGroupMember) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *APIGroupMember) GetMemberType() int32 {
	if x != nil {
		return x.MemberType
	}
	return 0
}

type APIAddMemberToGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string            `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Members []*APIGroupMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *APIAddMemberToGroupRequest) Reset() {
	*x = APIAddMemberToGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIAddMemberToGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIAddMemberToGroupRequest) ProtoMessage() {}

func (x *APIAddMemberToGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIAddMemberToGroupRequest.ProtoReflect.Descriptor instead.
func (*APIAddMemberToGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{6}
}

func (x *APIAddMemberToGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *APIAddMemberToGroupRequest) GetMembers() []*APIGroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type APIAddMemberToGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIAddMemberToGroupReply) Reset() {
	*x = APIAddMemberToGroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIAddMemberToGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIAddMemberToGroupReply) ProtoMessage() {}

func (x *APIAddMemberToGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIAddMemberToGroupReply.ProtoReflect.Descriptor instead.
func (*APIAddMemberToGroupReply) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{7}
}

type APIRemoveMemberFromGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Members []string `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *APIRemoveMemberFromGroupRequest) Reset() {
	*x = APIRemoveMemberFromGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRemoveMemberFromGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRemoveMemberFromGroupRequest) ProtoMessage() {}

func (x *APIRemoveMemberFromGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRemoveMemberFromGroupRequest.ProtoReflect.Descriptor instead.
func (*APIRemoveMemberFromGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{8}
}

func (x *APIRemoveMemberFromGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *APIRemoveMemberFromGroupRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type APIRemoveMemberFromGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIRemoveMemberFromGroupReply) Reset() {
	*x = APIRemoveMemberFromGroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRemoveMemberFromGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRemoveMemberFromGroupReply) ProtoMessage() {}

func (x *APIRemoveMemberFromGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRemoveMemberFromGroupReply.ProtoReflect.Descriptor instead.
func (*APIRemoveMemberFromGroupReply) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{9}
}

type APICreateGroupListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *APICreateGroupListData) Reset() {
	*x = APICreateGroupListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APICreateGroupListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICreateGroupListData) ProtoMessage() {}

func (x *APICreateGroupListData) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICreateGroupListData.ProtoReflect.Descriptor instead.
func (*APICreateGroupListData) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{10}
}

func (x *APICreateGroupListData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APICreateGroupListData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type APICreateGroupListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*APICreateGroupListData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *APICreateGroupListRequest) Reset() {
	*x = APICreateGroupListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APICreateGroupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICreateGroupListRequest) ProtoMessage() {}

func (x *APICreateGroupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICreateGroupListRequest.ProtoReflect.Descriptor instead.
func (*APICreateGroupListRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{11}
}

func (x *APICreateGroupListRequest) GetData() []*APICreateGroupListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type APICreateGroupListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId []string `protobuf:"bytes,1,rep,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *APICreateGroupListReply) Reset() {
	*x = APICreateGroupListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APICreateGroupListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICreateGroupListReply) ProtoMessage() {}

func (x *APICreateGroupListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICreateGroupListReply.ProtoReflect.Descriptor instead.
func (*APICreateGroupListReply) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{12}
}

func (x *APICreateGroupListReply) GetGroupId() []string {
	if x != nil {
		return x.GroupId
	}
	return nil
}

type APIDeleteGroupListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId []string `protobuf:"bytes,1,rep,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *APIDeleteGroupListRequest) Reset() {
	*x = APIDeleteGroupListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIDeleteGroupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDeleteGroupListRequest) ProtoMessage() {}

func (x *APIDeleteGroupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDeleteGroupListRequest.ProtoReflect.Descriptor instead.
func (*APIDeleteGroupListRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{13}
}

func (x *APIDeleteGroupListRequest) GetGroupId() []string {
	if x != nil {
		return x.GroupId
	}
	return nil
}

type APIDeleteGroupListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIDeleteGroupListReply) Reset() {
	*x = APIDeleteGroupListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIDeleteGroupListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDeleteGroupListReply) ProtoMessage() {}

func (x *APIDeleteGroupListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDeleteGroupListReply.ProtoReflect.Descriptor instead.
func (*APIDeleteGroupListReply) Descriptor() ([]byte, []int) {
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP(), []int{14}
}

var File_api_iam_service_v1_resources_iam_api_resource_v1_proto protoreflect.FileDescriptor

var file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDesc = []byte{
	0x0a, 0x36, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x61, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x69,
	0x61, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61,
	0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x61, 0x6d, 0x76, 0x31, 0x1a,
	0x23, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x15, 0x41, 0x50, 0x49, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x41, 0x50, 0x49, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x6f, 0x75, 0x72, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67,
	0x6f, 0x75, 0x72, 0x70, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x41, 0x50, 0x49, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x41, 0x50, 0x49, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x41, 0x50, 0x49,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x4c, 0x0a, 0x0e, 0x41, 0x50, 0x49, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x77,
	0x0a, 0x1a, 0x41, 0x50, 0x49, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x54, 0x6f,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61,
	0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x61, 0x6d, 0x76, 0x31, 0x2e,
	0x41, 0x50, 0x49, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x41, 0x50, 0x49, 0x41, 0x64,
	0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x55, 0x0a, 0x1f, 0x41, 0x50, 0x49, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x1f, 0x0a, 0x1d, 0x41, 0x50,
	0x49, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x46, 0x72, 0x6f,
	0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x4e, 0x0a, 0x16, 0x41,
	0x50, 0x49, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5e, 0x0a, 0x19, 0x41,
	0x50, 0x49, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x61, 0x6d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x69, 0x61, 0x6d, 0x76, 0x31, 0x2e, 0x41,
	0x50, 0x49, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x33, 0x0a, 0x17, 0x41,
	0x50, 0x49, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x22, 0x35, 0x0a, 0x19, 0x41, 0x50, 0x49, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x41, 0x50, 0x49, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x5c, 0x8a, 0x43, 0x08, 0x08, 0x91, 0xfb, 0xe2, 0x04, 0x10, 0x90, 0x03, 0x5a,
	0x4f, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6c, 0x61, 0x69, 0x6e, 0x75, 0x6f, 0x6e, 0x69,
	0x61, 0x6f, 0x2e, 0x63, 0x6e, 0x2f, 0x65, 0x64, 0x65, 0x6e, 0x2d, 0x71, 0x75, 0x61, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x69, 0x61, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x3b, 0x69, 0x61, 0x6d, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescOnce sync.Once
	file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescData = file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDesc
)

func file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescGZIP() []byte {
	file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescOnce.Do(func() {
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescData)
	})
	return file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDescData
}

var file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_iam_service_v1_resources_iam_api_resource_v1_proto_goTypes = []interface{}{
	(*APICreateGroupRequest)(nil),           // 0: api.iam.service.iamv1.APICreateGroupRequest
	(*APICreateGroupReply)(nil),             // 1: api.iam.service.iamv1.APICreateGroupReply
	(*APIGetGroupRequest)(nil),              // 2: api.iam.service.iamv1.APIGetGroupRequest
	(*APIDeleteGroupRequest)(nil),           // 3: api.iam.service.iamv1.APIDeleteGroupRequest
	(*APIDeleteGroupReply)(nil),             // 4: api.iam.service.iamv1.APIDeleteGroupReply
	(*APIGroupMember)(nil),                  // 5: api.iam.service.iamv1.APIGroupMember
	(*APIAddMemberToGroupRequest)(nil),      // 6: api.iam.service.iamv1.APIAddMemberToGroupRequest
	(*APIAddMemberToGroupReply)(nil),        // 7: api.iam.service.iamv1.APIAddMemberToGroupReply
	(*APIRemoveMemberFromGroupRequest)(nil), // 8: api.iam.service.iamv1.APIRemoveMemberFromGroupRequest
	(*APIRemoveMemberFromGroupReply)(nil),   // 9: api.iam.service.iamv1.APIRemoveMemberFromGroupReply
	(*APICreateGroupListData)(nil),          // 10: api.iam.service.iamv1.APICreateGroupListData
	(*APICreateGroupListRequest)(nil),       // 11: api.iam.service.iamv1.APICreateGroupListRequest
	(*APICreateGroupListReply)(nil),         // 12: api.iam.service.iamv1.APICreateGroupListReply
	(*APIDeleteGroupListRequest)(nil),       // 13: api.iam.service.iamv1.APIDeleteGroupListRequest
	(*APIDeleteGroupListReply)(nil),         // 14: api.iam.service.iamv1.APIDeleteGroupListReply
}
var file_api_iam_service_v1_resources_iam_api_resource_v1_proto_depIdxs = []int32{
	5,  // 0: api.iam.service.iamv1.APIAddMemberToGroupRequest.members:type_name -> api.iam.service.iamv1.APIGroupMember
	10, // 1: api.iam.service.iamv1.APICreateGroupListRequest.data:type_name -> api.iam.service.iamv1.APICreateGroupListData
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_iam_service_v1_resources_iam_api_resource_v1_proto_init() }
func file_api_iam_service_v1_resources_iam_api_resource_v1_proto_init() {
	if File_api_iam_service_v1_resources_iam_api_resource_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APICreateGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APICreateGroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIGetGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIDeleteGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIDeleteGroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIGroupMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIAddMemberToGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIAddMemberToGroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRemoveMemberFromGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRemoveMemberFromGroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APICreateGroupListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APICreateGroupListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APICreateGroupListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIDeleteGroupListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIDeleteGroupListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_iam_service_v1_resources_iam_api_resource_v1_proto_goTypes,
		DependencyIndexes: file_api_iam_service_v1_resources_iam_api_resource_v1_proto_depIdxs,
		MessageInfos:      file_api_iam_service_v1_resources_iam_api_resource_v1_proto_msgTypes,
	}.Build()
	File_api_iam_service_v1_resources_iam_api_resource_v1_proto = out.File
	file_api_iam_service_v1_resources_iam_api_resource_v1_proto_rawDesc = nil
	file_api_iam_service_v1_resources_iam_api_resource_v1_proto_goTypes = nil
	file_api_iam_service_v1_resources_iam_api_resource_v1_proto_depIdxs = nil
}
