// Code generated by protoc-gen-go-fx. DO NOT EDIT.
// versions:
// 	protoc-gen-go-fx v1.32.0-devel
// 	protoc        v5.26.1
// source: api/proto-common/v3/resources/common.resource.proto

package common_resources

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"` // field 为需要排序的字段，具体的含义由接口定义，一般为排序的字段名
	Desc  bool   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`  // desc 为 True 时说明为倒序，否则为正序
}

func (x *SortField) Reset() {
	*x = SortField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortField) ProtoMessage() {}

func (x *SortField) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortField.ProtoReflect.Descriptor instead.
func (*SortField) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v3_resources_common_resource_proto_rawDescGZIP(), []int{0}
}

func (x *SortField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortField) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type Paging struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      int32        `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                            // Page 为本次所需的页码
	PageSize  int32        `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    // PageSize 为每页所需数据的数量
	Count     int64        `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                          // count 为符合查询条件的数据量
	HasNext   bool         `protobuf:"varint,4,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`       // has_next 表示是否存在下一页
	Sort      []*SortField `protobuf:"bytes,5,rep,name=sort,proto3" json:"sort,omitempty"`                             // sort 为本次查询的排序条件
	NeedCount bool         `protobuf:"varint,6,opt,name=need_count,json=needCount,proto3" json:"need_count,omitempty"` // need_count 表示是否需要统计总数
}

func (x *Paging) Reset() {
	*x = Paging{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paging) ProtoMessage() {}

func (x *Paging) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paging.ProtoReflect.Descriptor instead.
func (*Paging) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v3_resources_common_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Paging) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Paging) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Paging) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Paging) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *Paging) GetSort() []*SortField {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *Paging) GetNeedCount() bool {
	if x != nil {
		return x.NeedCount
	}
	return false
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// code 为本次接口的调用结果，后续将使用统一的 StatusCode 管理所有状态码, 当前版本的 code 将统一从 StatusCode 的 Number 获取
	Code       int32  `protobuf:"varint,9001,opt,name=code,proto3" json:"code,omitempty"`
	Reason     string `protobuf:"bytes,9002,opt,name=reason,proto3" json:"reason,omitempty"`                           // reason 为 code 对应的英文编码，可用于快速定位问题
	Message    string `protobuf:"bytes,9003,opt,name=message,proto3" json:"message,omitempty"`                         // message 为接口调用出错时的具体错误信息
	Identity   string `protobuf:"bytes,9004,opt,name=identity,proto3" json:"identity,omitempty"`                       // identity 为本次调用的通用结果，如某些接口调用后只需返回一个 Id 或标识符，则可使用该字段携带信息
	TraceId    string `protobuf:"bytes,9005,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`          // trace_id 为本次调用的链路 Id，可用于整合所有本次调用相关的线索
	ErrorChain string `protobuf:"bytes,9006,opt,name=error_chain,json=errorChain,proto3" json:"error_chain,omitempty"` // error_chain 如果错误经过了多层业务的封装，则可以从该字段得到每一层的错误信息
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v3_resources_common_resource_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Result) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Result) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Result) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Result) GetErrorChain() string {
	if x != nil {
		return x.ErrorChain
	}
	return ""
}

type DBModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32                  `protobuf:"varint,10001,opt,name=id,proto3" json:"id,omitempty" db:"id"`                                            // 主键
	IsDeleted  bool                   `protobuf:"varint,10002,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty" db:"is_deleted"`     // 是否已删除
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,10003,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" "db:"create_time"` // 创建时间
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,10004,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty" "db:"update_time"` // 更新时间
}

func (x *DBModel) Reset() {
	*x = DBModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBModel) ProtoMessage() {}

func (x *DBModel) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBModel.ProtoReflect.Descriptor instead.
func (*DBModel) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v3_resources_common_resource_proto_rawDescGZIP(), []int{3}
}

func (x *DBModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DBModel) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *DBModel) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *DBModel) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type FlattenRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reserved *Reserved `protobuf:"bytes,1,opt,name=reserved,proto3,oneof" json:"reserved,omitempty"`
}

func (x *FlattenRules) Reset() {
	*x = FlattenRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlattenRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlattenRules) ProtoMessage() {}

func (x *FlattenRules) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlattenRules.ProtoReflect.Descriptor instead.
func (*FlattenRules) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v3_resources_common_resource_proto_rawDescGZIP(), []int{4}
}

func (x *FlattenRules) GetReserved() *Reserved {
	if x != nil {
		return x.Reserved
	}
	return nil
}

type Reserved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min *int32 `protobuf:"varint,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max *int32 `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
}

func (x *Reserved) Reset() {
	*x = Reserved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserved) ProtoMessage() {}

func (x *Reserved) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_v3_resources_common_resource_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserved.ProtoReflect.Descriptor instead.
func (*Reserved) Descriptor() ([]byte, []int) {
	return file_api_proto_common_v3_resources_common_resource_proto_rawDescGZIP(), []int{5}
}

func (x *Reserved) GetMin() int32 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *Reserved) GetMax() int32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

var file_api_proto_common_v3_resources_common_resource_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FlattenRules)(nil),
		Field:         1423,
		Name:          "proto_common.common.flatten_rule",
		Tag:           "bytes,1423,opt,name=flatten_rule",
		Filename:      "api/proto-common/v3/resources/common.resource.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1424,
		Name:          "proto_common.common.flatten",
		Tag:           "varint,1424,opt,name=flatten",
		Filename:      "api/proto-common/v3/resources/common.resource.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional proto_common.common.FlattenRules flatten_rule = 1423;
	E_FlattenRule = &file_api_proto_common_v3_resources_common_resource_proto_extTypes[0]
	// optional bool flatten = 1424;
	E_Flatten = &file_api_proto_common_v3_resources_common_resource_proto_extTypes[1]
)

var File_api_proto_common_v3_resources_common_resource_proto protoreflect.FileDescriptor

var file_api_proto_common_v3_resources_common_resource_proto_rawDesc = []byte{
	0x0a, 0x33, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x76, 0x33, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x74,
	0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x35, 0x0a, 0x09, 0x53, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0xbd, 0x01, 0x0a, 0x06, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68,
	0x61, 0x73, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68,
	0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x12, 0x32, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65,
	0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x6e, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xb5, 0x01, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xa9, 0x46, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x28, 0x00, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x17, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0xaa, 0x46, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0xab, 0x46, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0xac, 0x46, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0xad, 0x46, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0xae,
	0x46, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x22, 0xb6, 0x01, 0x0a, 0x07, 0x44, 0x42, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0f, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x91, 0x4e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x92, 0x4e, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x3c,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x93, 0x4e,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0b,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x94, 0x4e, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x0c, 0x46, 0x6c,
	0x61, 0x74, 0x74, 0x65, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x22, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x64, 0x12, 0x15, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x6d, 0x61,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x88, 0x01,
	0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d, 0x69, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d, 0x61,
	0x78, 0x3a, 0x67, 0x0a, 0x0c, 0x66, 0x6c, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x5f, 0x72, 0x75, 0x6c,
	0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x8f, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x6c,
	0x61, 0x74, 0x74, 0x65, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x0b, 0x66, 0x6c, 0x61, 0x74,
	0x74, 0x65, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x3a, 0x3b, 0x0a, 0x07, 0x66, 0x6c,
	0x61, 0x74, 0x74, 0x65, 0x6e, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x90, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x66, 0x6c, 0x61,
	0x74, 0x74, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x5d, 0x5a, 0x5b, 0x67, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2e, 0x6c, 0x61, 0x69, 0x6e, 0x75, 0x6f, 0x6e, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6e, 0x2f,
	0x65, 0x64, 0x65, 0x6e, 0x2d, 0x71, 0x75, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x33, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_common_v3_resources_common_resource_proto_rawDescOnce sync.Once
	file_api_proto_common_v3_resources_common_resource_proto_rawDescData = file_api_proto_common_v3_resources_common_resource_proto_rawDesc
)

func file_api_proto_common_v3_resources_common_resource_proto_rawDescGZIP() []byte {
	file_api_proto_common_v3_resources_common_resource_proto_rawDescOnce.Do(func() {
		file_api_proto_common_v3_resources_common_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_common_v3_resources_common_resource_proto_rawDescData)
	})
	return file_api_proto_common_v3_resources_common_resource_proto_rawDescData
}

var file_api_proto_common_v3_resources_common_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_common_v3_resources_common_resource_proto_goTypes = []interface{}{
	(*SortField)(nil),                 // 0: proto_common.common.SortField
	(*Paging)(nil),                    // 1: proto_common.common.Paging
	(*Result)(nil),                    // 2: proto_common.common.Result
	(*DBModel)(nil),                   // 3: proto_common.common.DBModel
	(*FlattenRules)(nil),              // 4: proto_common.common.FlattenRules
	(*Reserved)(nil),                  // 5: proto_common.common.Reserved
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
	(*descriptorpb.FieldOptions)(nil), // 7: google.protobuf.FieldOptions
}
var file_api_proto_common_v3_resources_common_resource_proto_depIdxs = []int32{
	0, // 0: proto_common.common.Paging.sort:type_name -> proto_common.common.SortField
	6, // 1: proto_common.common.DBModel.create_time:type_name -> google.protobuf.Timestamp
	6, // 2: proto_common.common.DBModel.update_time:type_name -> google.protobuf.Timestamp
	5, // 3: proto_common.common.FlattenRules.reserved:type_name -> proto_common.common.Reserved
	7, // 4: proto_common.common.flatten_rule:extendee -> google.protobuf.FieldOptions
	7, // 5: proto_common.common.flatten:extendee -> google.protobuf.FieldOptions
	4, // 6: proto_common.common.flatten_rule:type_name -> proto_common.common.FlattenRules
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	6, // [6:7] is the sub-list for extension type_name
	4, // [4:6] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_common_v3_resources_common_resource_proto_init() }
func file_api_proto_common_v3_resources_common_resource_proto_init() {
	if File_api_proto_common_v3_resources_common_resource_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_common_v3_resources_common_resource_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_common_v3_resources_common_resource_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paging); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_common_v3_resources_common_resource_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_common_v3_resources_common_resource_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_common_v3_resources_common_resource_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlattenRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_common_v3_resources_common_resource_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reserved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_common_v3_resources_common_resource_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_api_proto_common_v3_resources_common_resource_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_common_v3_resources_common_resource_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_common_v3_resources_common_resource_proto_goTypes,
		DependencyIndexes: file_api_proto_common_v3_resources_common_resource_proto_depIdxs,
		MessageInfos:      file_api_proto_common_v3_resources_common_resource_proto_msgTypes,
		ExtensionInfos:    file_api_proto_common_v3_resources_common_resource_proto_extTypes,
	}.Build()
	File_api_proto_common_v3_resources_common_resource_proto = out.File
	file_api_proto_common_v3_resources_common_resource_proto_rawDesc = nil
	file_api_proto_common_v3_resources_common_resource_proto_goTypes = nil
	file_api_proto_common_v3_resources_common_resource_proto_depIdxs = nil
}
