// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/email-service/v1/resources/email.email.resource.v1.proto

package emailv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SendEmailRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SendEmailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendEmailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendEmailRequestMultiError, or nil if none found.
func (m *SendEmailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendEmailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for From

	// no validation rules for To

	// no validation rules for Subject

	// no validation rules for Body

	if len(errors) > 0 {
		return SendEmailRequestMultiError(errors)
	}

	return nil
}

// SendEmailRequestMultiError is an error wrapping multiple validation errors
// returned by SendEmailRequest.ValidateAll() if the designated constraints
// aren't met.
type SendEmailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendEmailRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendEmailRequestMultiError) AllErrors() []error { return m }

// SendEmailRequestValidationError is the validation error returned by
// SendEmailRequest.Validate if the designated constraints aren't met.
type SendEmailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendEmailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendEmailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendEmailRequestValidationError) Cause() error { return e.cause }

func (e SendEmailRequestValidationError) Code() int64 { return 10010001 }

func (e SendEmailRequestValidationError) HttpCode() int64 { return 400 }

// Key function returns key value.
func (e SendEmailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendEmailRequestValidationError) ErrorName() string { return "SendEmailRequestValidationError" }

// Error satisfies the builtin error interface
func (e SendEmailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendEmailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendEmailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Code() int64
	HttpCode() int64
	Cause() error
	ErrorName() string
} = SendEmailRequestValidationError{}

// Validate checks the field values on SendEmailReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SendEmailReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendEmailReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SendEmailReplyMultiError,
// or nil if none found.
func (m *SendEmailReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SendEmailReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	if len(errors) > 0 {
		return SendEmailReplyMultiError(errors)
	}

	return nil
}

// SendEmailReplyMultiError is an error wrapping multiple validation errors
// returned by SendEmailReply.ValidateAll() if the designated constraints
// aren't met.
type SendEmailReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendEmailReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendEmailReplyMultiError) AllErrors() []error { return m }

// SendEmailReplyValidationError is the validation error returned by
// SendEmailReply.Validate if the designated constraints aren't met.
type SendEmailReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendEmailReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendEmailReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendEmailReplyValidationError) Cause() error { return e.cause }

func (e SendEmailReplyValidationError) Code() int64 { return 10010001 }

func (e SendEmailReplyValidationError) HttpCode() int64 { return 400 }

// Key function returns key value.
func (e SendEmailReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendEmailReplyValidationError) ErrorName() string { return "SendEmailReplyValidationError" }

// Error satisfies the builtin error interface
func (e SendEmailReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendEmailReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendEmailReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Code() int64
	HttpCode() int64
	Cause() error
	ErrorName() string
} = SendEmailReplyValidationError{}
