// Code generated by protoc-gen-go-fx. DO NOT EDIT.
// versions:
// 	protoc-gen-go-fx v1.32.0-devel
// 	protoc        v5.26.1
// source: api/common/v1/env/env.v1.proto

package envv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeEnvEnum_RuntimeEnv int32

const (
	// UNKNOWN 未知
	RuntimeEnvEnum_UNKNOWN RuntimeEnvEnum_RuntimeEnv = 0
	// LOCAL 本地开发
	RuntimeEnvEnum_LOCAL RuntimeEnvEnum_RuntimeEnv = 1
	// DEVELOP 开发环境
	RuntimeEnvEnum_DEVELOP RuntimeEnvEnum_RuntimeEnv = 2
	// TESTING 测试环境
	RuntimeEnvEnum_TESTING RuntimeEnvEnum_RuntimeEnv = 3
	// PREVIEW 预发布 环境
	RuntimeEnvEnum_PREVIEW RuntimeEnvEnum_RuntimeEnv = 4
	// PRODUCTION 生产环境
	RuntimeEnvEnum_PRODUCTION RuntimeEnvEnum_RuntimeEnv = 5
)

// Enum value maps for RuntimeEnvEnum_RuntimeEnv.
var (
	RuntimeEnvEnum_RuntimeEnv_name = map[int32]string{
		0: "UNKNOWN",
		1: "LOCAL",
		2: "DEVELOP",
		3: "TESTING",
		4: "PREVIEW",
		5: "PRODUCTION",
	}
	RuntimeEnvEnum_RuntimeEnv_value = map[string]int32{
		"UNKNOWN":    0,
		"LOCAL":      1,
		"DEVELOP":    2,
		"TESTING":    3,
		"PREVIEW":    4,
		"PRODUCTION": 5,
	}
)

func (x RuntimeEnvEnum_RuntimeEnv) Enum() *RuntimeEnvEnum_RuntimeEnv {
	p := new(RuntimeEnvEnum_RuntimeEnv)
	*p = x
	return p
}

func (x RuntimeEnvEnum_RuntimeEnv) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeEnvEnum_RuntimeEnv) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_env_env_v1_proto_enumTypes[0].Descriptor()
}

func (RuntimeEnvEnum_RuntimeEnv) Type() protoreflect.EnumType {
	return &file_api_common_v1_env_env_v1_proto_enumTypes[0]
}

func (x RuntimeEnvEnum_RuntimeEnv) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeEnvEnum_RuntimeEnv.Descriptor instead.
func (RuntimeEnvEnum_RuntimeEnv) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_env_env_v1_proto_rawDescGZIP(), []int{0, 0}
}

// RuntimeEnvEnum app运行环境
type RuntimeEnvEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuntimeEnvEnum) Reset() {
	*x = RuntimeEnvEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_v1_env_env_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeEnvEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEnvEnum) ProtoMessage() {}

func (x *RuntimeEnvEnum) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_env_env_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEnvEnum.ProtoReflect.Descriptor instead.
func (*RuntimeEnvEnum) Descriptor() ([]byte, []int) {
	return file_api_common_v1_env_env_v1_proto_rawDescGZIP(), []int{0}
}

var File_api_common_v1_env_env_v1_proto protoreflect.FileDescriptor

var file_api_common_v1_env_env_v1_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f,
	0x65, 0x6e, 0x76, 0x2f, 0x65, 0x6e, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x65, 0x6e, 0x76,
	0x76, 0x31, 0x22, 0x6d, 0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x76,
	0x45, 0x6e, 0x75, 0x6d, 0x22, 0x5b, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x45,
	0x6e, 0x76, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45,
	0x56, 0x45, 0x4c, 0x4f, 0x50, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x45, 0x53, 0x54, 0x49,
	0x4e, 0x47, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x45, 0x56, 0x49, 0x45, 0x57, 0x10,
	0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x05, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6c, 0x61, 0x69, 0x6e,
	0x75, 0x6f, 0x6e, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6e, 0x2f, 0x65, 0x64, 0x65, 0x6e, 0x2d, 0x71,
	0x75, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f,
	0x65, 0x6e, 0x76, 0x3b, 0x65, 0x6e, 0x76, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_common_v1_env_env_v1_proto_rawDescOnce sync.Once
	file_api_common_v1_env_env_v1_proto_rawDescData = file_api_common_v1_env_env_v1_proto_rawDesc
)

func file_api_common_v1_env_env_v1_proto_rawDescGZIP() []byte {
	file_api_common_v1_env_env_v1_proto_rawDescOnce.Do(func() {
		file_api_common_v1_env_env_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_common_v1_env_env_v1_proto_rawDescData)
	})
	return file_api_common_v1_env_env_v1_proto_rawDescData
}

var file_api_common_v1_env_env_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_common_v1_env_env_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_common_v1_env_env_v1_proto_goTypes = []interface{}{
	(RuntimeEnvEnum_RuntimeEnv)(0), // 0: api.common.envv1.RuntimeEnvEnum.RuntimeEnv
	(*RuntimeEnvEnum)(nil),         // 1: api.common.envv1.RuntimeEnvEnum
}
var file_api_common_v1_env_env_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_common_v1_env_env_v1_proto_init() }
func file_api_common_v1_env_env_v1_proto_init() {
	if File_api_common_v1_env_env_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_common_v1_env_env_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeEnvEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_common_v1_env_env_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_env_env_v1_proto_goTypes,
		DependencyIndexes: file_api_common_v1_env_env_v1_proto_depIdxs,
		EnumInfos:         file_api_common_v1_env_env_v1_proto_enumTypes,
		MessageInfos:      file_api_common_v1_env_env_v1_proto_msgTypes,
	}.Build()
	File_api_common_v1_env_env_v1_proto = out.File
	file_api_common_v1_env_env_v1_proto_rawDesc = nil
	file_api_common_v1_env_env_v1_proto_goTypes = nil
	file_api_common_v1_env_env_v1_proto_depIdxs = nil
}
