// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.1
// - protoc             v5.26.1
// source: api/sms-service/v1/services/sms.sms.service.v1.proto

package smsservicev1

import (
	context "context"
	fmt "fmt"

	client "gitlab.lainuoniao.cn/eden-quan/go-biz-kit/client"
	def "gitlab.lainuoniao.cn/eden-quan/go-biz-kit/config/def"
	resources "gitlab.lainuoniao.cn/eden-quan/proto-service/api/sms-service/v1/resources"
	fx "go.uber.org/fx"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7
const _ = fx.Version

var _ = new(fmt.Stringer)
var _ = new(def.Server)
var _ = new(client.RegisterGRPCClientFactoryType)

const (
	SMSServiceV1_SendSMS_FullMethodName = "/api.sms.service.smsservicev1.SMSServiceV1/SendSMS"
)

// SMSServiceV1Client is the client API for SMSServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SMSServiceV1Client interface {
	SendSMS(ctx context.Context, in *resources.SendSMSRequest, opts ...grpc.CallOption) (*resources.SendSMSReply, error)
	RegisterNameForDiscover() string
}

type sMSServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func (c *sMSServiceV1Client) RegisterNameForDiscover() string {
	return "/sms-service/v1"
}

func newSMSServiceV1Client(cc grpc.ClientConnInterface) SMSServiceV1Client {
	return &sMSServiceV1Client{cc}
}

func registerSMSServiceV1ClientGRPCNameProvider() []string {
	return []string{"/sms-service/v1", "grpc"}
}

// RegisterSMSServiceV1ClientGRPCProvider is the provider for injection framework
// creator is the factory function which use to create the SMSServiceV1Client instance/implement
// the creator function receive dependency provided by fx to create ClientInterface,
// and returns the new dependency can use by others functions
func RegisterSMSServiceV1ClientGRPCProvider(creator interface{}) []interface{} {
	return []interface{}{
		fx.Annotate(
			newSMSServiceV1Client,
			fx.As(new(SMSServiceV1Client)),
			fx.ParamTags(`name:"/sms-service/v1/grpc/sMSServiceV1"`),
		),
		fx.Annotate(
			creator,
			fx.As(new(grpc.ClientConnInterface)),
			fx.ParamTags(`name:"/sms-service/v1/grpc/name/sMSServiceV1"`),
			fx.ResultTags(`name:"/sms-service/v1/grpc/sMSServiceV1"`),
		),
		fx.Annotate(
			registerSMSServiceV1ClientGRPCNameProvider,
			fx.ResultTags(`name:"/sms-service/v1/grpc/name/sMSServiceV1"`),
		),
	}
}

type SMSServiceV1ClientGRPCFactory interface {
	New(conf *def.Server) (SMSServiceV1Client, error)
}

type sMSServiceV1ClientGRPCFactoryImpl struct {
	factory client.RegisterGRPCClientFactoryType
}

func (p *sMSServiceV1ClientGRPCFactoryImpl) New(conf *def.Server) (SMSServiceV1Client, error) {
	cc, err := p.factory(conf)
	if err != nil {
		return nil, fmt.Errorf("create SMSServiceV1Client failed cause %s", err)
	}
	return &sMSServiceV1Client{cc: cc}, nil
}

func RegisterSMSServiceV1ClientGRPCFactoryProvider(factory client.RegisterGRPCClientFactoryType) SMSServiceV1ClientGRPCFactory {
	return &sMSServiceV1ClientGRPCFactoryImpl{factory: factory}
}

func (c *sMSServiceV1Client) SendSMS(ctx context.Context, in *resources.SendSMSRequest, opts ...grpc.CallOption) (*resources.SendSMSReply, error) {
	out := new(resources.SendSMSReply)
	err := c.cc.Invoke(ctx, SMSServiceV1_SendSMS_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SMSServiceV1Server is the server API for SMSServiceV1 service.
// All implementations must embed UnimplementedSMSServiceV1Server
// for forward compatibility
type SMSServiceV1Server interface {
	SendSMS(context.Context, *resources.SendSMSRequest) (*resources.SendSMSReply, error)
	mustEmbedUnimplementedSMSServiceV1Server()
}

// Generate Injection
type registerSMSServiceV1ServerGRPCResult struct{}

func (*registerSMSServiceV1ServerGRPCResult) String() string {
	return "SMSServiceV1ServerGRPCServer"
}

func RegisterSMSServiceV1ServerGRPCProvider(newer interface{}) []interface{} {
	return []interface{}{
		// For provide dependency
		fx.Annotate(
			newer,
			fx.As(new(SMSServiceV1Server)),
		),
		// For create instance
		fx.Annotate(
			registerSMSServiceV1ServerProviderImpl,
			fx.As(new(fmt.Stringer)),
			fx.ResultTags(`group:"grpc_register"`),
		),
	}
}

// registerSMSServiceV1ServerProviderImpl use to trigger register
func registerSMSServiceV1ServerProviderImpl(s grpc.ServiceRegistrar, srv SMSServiceV1Server) *registerSMSServiceV1ServerGRPCResult {
	registerSMSServiceV1Server(s, srv)
	return &registerSMSServiceV1ServerGRPCResult{}
}

// UnimplementedSMSServiceV1Server must be embedded to have forward compatible implementations.
type UnimplementedSMSServiceV1Server struct {
}

func (UnimplementedSMSServiceV1Server) SendSMS(context.Context, *resources.SendSMSRequest) (*resources.SendSMSReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSMS not implemented")
}
func (UnimplementedSMSServiceV1Server) mustEmbedUnimplementedSMSServiceV1Server() {}

// UnsafeSMSServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SMSServiceV1Server will
// result in compilation errors.
type UnsafeSMSServiceV1Server interface {
	mustEmbedUnimplementedSMSServiceV1Server()
}

func registerSMSServiceV1Server(s grpc.ServiceRegistrar, srv SMSServiceV1Server) {
	s.RegisterService(&SMSServiceV1_ServiceDesc, srv)
}

func _SMSServiceV1_SendSMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.SendSMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSServiceV1Server).SendSMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMSServiceV1_SendSMS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSServiceV1Server).SendSMS(ctx, req.(*resources.SendSMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SMSServiceV1_ServiceDesc is the grpc.ServiceDesc for SMSServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SMSServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.sms.service.smsservicev1.SMSServiceV1",
	HandlerType: (*SMSServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSMS",
			Handler:    _SMSServiceV1_SendSMS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/sms-service/v1/services/sms.sms.service.v1.proto",
}
